### PR TITLE
MNT: Re-rendered with conda-build 3.18.11 and conda-smithy 3.7.5

### PR DESCRIPTION
**Pull request by st3107**

### CODE REVIEW

**Comment by st3107** [comment]
Hello, @mrakitin . I fixed a small bug in the xpdsim and release a new version. Could you review it? Thank you.

**Comment by st3107** [comment]
Hi @mrakitin . The build failed because of conflicts in dependencies. However, I didn't change the dependencies at all and the build is successful on master branch. Could you give me some hints why this build reports conflicts in dependencies?

**Comment by mrakitin** [comment]
Did you add the flexible channel priority parameter?

**Comment by st3107** [comment]
@mrakitin Thank you for reminder. I just added it.

**Comment by st3107** [comment]
CI passed. Ready to merge.

**Review by mrakitin — APPROVED** [review]

**Pull request merged**
